apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: remove-self-provisioner
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: access-remove-self-provisioner
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  annotations:
                    rbac.authorization.kubernetes.io/autoupdate: "false"
                  name: self-provisioners
                subjects: null
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: self-provisioner
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-access-remove-self-provisioner
placementRef:
  name: placement-access-remove-self-provisioner
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: remove-self-provisioner
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-access-remove-self-provisioner
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: "cluster.open-cluster-management.io/clusterset", operator: In, values: ["dev"]}

