apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: mybank-custom-profile
  # annotations:
  #   compliance.openshift.io/product-type: Platform 
spec:
  extends: ocp4-cis
  description: This is myBank custom compliance profile 
  title: mybank custom profile
  # enableRules:
    # - name: ocp4-kubeadmin-removed
    #   rationale: The rules is mandated by the regulators
    # - name: ocp4-rbac-wildcard-use
    #   rationale: The rules is mandated by the regulators
  # disableRules:
  #   - name: ocp4-audit-profile-set
  #     rationale: This does not apply to the cluster
  #   - name: ocp4-configure-network-policies-namespaces
  #     rationale: This does not apply to the cluster
  #   - name: ocp4-scc-limit-container-allowed-capabilities
  #     rationale: We use third party software that installs its own SCC with extra privileges
  #   - name: ocp4-kubeadmin-removed
  #     rationale: We use third party software that installs its own SCC with extra privileges
  #   - name: ocp4-rbac-wildcard-use
  #     rationale: The rules is mandated by the regulators
  manualRules:
    - name: ocp4-audit-profile-set
      rationale: This does not apply to the cluster
    - name: ocp4-configure-network-policies-namespaces
      rationale: This does not apply to the cluster
    - name: ocp4-scc-limit-container-allowed-capabilities
      rationale: We use third party software that installs its own SCC with extra privileges
    - name: ocp4-kubeadmin-removed
      rationale: We use third party software that installs its own SCC with extra privileges
    - name: ocp4-rbac-wildcard-use
      rationale: The rules is mandated by the regulators

# 99 rules are there in the `ocp4-cis` profile
# ACS show __ controls for the profile `ocp4-cis`
# scaponu - 87 rules with 92%

# ACS show 94 controls for the tailored profile `mybank-custom-profile`


# with no rules added
# scapn 92 rules and 86.1% score

# ACS show 94 controls for the tailored profile `mybank-custom-profile`
# 90% score



# ACS scan of ocp4-cis
# 99 controls with 90% score